name: check_code_quality
on: pull_request
jobs:
  ruff:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Install uv
        uses: astral-sh/setup-uv@v7.3.0
